"/start" : "Start"
"/stop" : "Stop"
"/add_date_of_birth" : "AddDateOfBirth"
"/show_vacations" : "ShowVacations"
"/add_vacation" : "AddVacation"
"/remove_vacation" : "RemoveVacation"
"/weather" : "Weather"